using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using UnityEngine;

namespace Luau.Unity
{
    public sealed class LuauUnityOptions
    {
        public const int DefaultMaxPrintArguments = 32;
        public const int DefaultMaxPrintUtf8Bytes = 4 * 1024;
        public const int DefaultMaxPrintMessagesPerSecond = 20;

        public bool OpenStandardLibraries { get; set; } = true;

        /// <summary>
        /// Gets or sets whether the privileged debug library is opened before
        /// root sandboxing. Leave disabled for untrusted mods.
        /// </summary>
        public bool OpenDebugLibrary { get; set; }

        /// <summary>
        /// Gets or sets whether the root globals and opened API tables are
        /// frozen after host configuration. Disabling this is a privileged
        /// host opt-out and must not be used for untrusted mods.
        /// </summary>
        public bool SandboxRoot { get; set; } = true;

        /// <summary>
        /// Gets or sets whether state creation captures the current Unity
        /// synchronization context when no continuation scheduler is already
        /// configured. Enabled by default so asynchronous Luau execution
        /// resumes on the Unity main thread.
        /// </summary>
        public bool CaptureUnitySynchronizationContext { get; set; } = true;

        /// <summary>
        /// Gets or sets whether persistent bytecode generated by the package's
        /// first-party importer is admitted through the generated build
        /// manifest. Disabled by default so ordinary and mod states continue
        /// to reject persistent bytecode.
        /// </summary>
        public bool UseFirstPartyBytecode { get; set; }

        /// <summary>
        /// Gets or sets an explicit continuation scheduler. When set, this
        /// overrides the scheduler in
        /// <see cref="LuauStateOptions.DefaultExecutionOptions"/>.
        /// </summary>
        public ILuauContinuationScheduler ContinuationScheduler { get; set; }

        /// <summary>
        /// Gets or sets the root-state policy. The default is finite and
        /// suitable as a conservative starting point for untrusted mods.
        /// Assigning another instance explicitly replaces that complete
        /// policy, including its limits.
        /// </summary>
        public LuauStateOptions StateOptions { get; set; } = LuauStateOptions.Default;

        /// <summary>
        /// Gets or sets the immutable, source-only module namespace exposed as
        /// <c>require()</c>. A null map leaves <c>require()</c> unavailable.
        /// Use a distinct map for each mod namespace.
        /// </summary>
        public LuauModuleMap ModuleMap { get; set; }

        public Action<LuauState> ConfigureHostApis { get; set; }
        public Action<string> Log { get; set; }

        /// <summary>
        /// Gets or sets the maximum number of values formatted by one call to
        /// the default Unity <c>print</c> function. Additional values are
        /// replaced by a truncation marker.
        /// </summary>
        public int MaxPrintArguments { get; set; } = DefaultMaxPrintArguments;

        /// <summary>
        /// Gets or sets the maximum UTF-8 size of the message emitted by one
        /// call to the default Unity <c>print</c> function.
        /// </summary>
        public int MaxPrintUtf8Bytes { get; set; } = DefaultMaxPrintUtf8Bytes;

        /// <summary>
        /// Gets or sets the maximum number of messages emitted by the default
        /// Unity <c>print</c> function in each one-second window. Extra
        /// calls are discarded before formatting their arguments. Set null
        /// only for explicitly trusted content.
        /// </summary>
        public int? MaxPrintMessagesPerSecond { get; set; } =
            DefaultMaxPrintMessagesPerSecond;
    }

    public static partial class LuauUnity
    {
        static readonly object TrackedRootsGate = new object();
        static readonly List<WeakReference<LuauState>> TrackedRoots =
            new List<WeakReference<LuauState>>();
        static bool trackedRootAdmissionStopping;

        public static LuauState CreateState(LuauUnityOptions options = null)
        {
            options = options ?? new LuauUnityOptions();

            var stateOptions = ResolveStateOptions(options);
            var state = CreateTrackedState(stateOptions);
            try
            {
                if (options.OpenStandardLibraries)
                {
                    OpenUnityStandardLibraries(state);
                }

                if (options.OpenDebugLibrary)
                {
                    state.OpenDebugLibrary();
                }

                RegisterPrint(
                    state,
                    options.Log,
                    options.MaxPrintArguments,
                    options.MaxPrintUtf8Bytes,
                    options.MaxPrintMessagesPerSecond);

                if (options.ModuleMap != null)
                {
                    state.OpenRequireLibrary(options.ModuleMap);
                }

                options.ConfigureHostApis?.Invoke(state);

                if (options.SandboxRoot)
                {
                    state.SandboxRoot();
                }

                if (state.IsDisposed)
                {
                    throw new ObjectDisposedException(
                        nameof(LuauState),
                        "The Luau root was disposed during Unity lifecycle teardown.");
                }

                return state;
            }
            catch
            {
                state.Dispose();
                throw;
            }
        }

        static LuauState CreateTrackedState(LuauStateOptions stateOptions)
        {
            lock (TrackedRootsGate)
            {
                if (trackedRootAdmissionStopping)
                {
                    throw new ObjectDisposedException(
                        nameof(LuauUnity),
                        "Luau root admission has stopped for Unity lifecycle teardown.");
                }

                for (var index = TrackedRoots.Count - 1; index >= 0; index--)
                {
                    if (!TrackedRoots[index].TryGetTarget(out var tracked) || tracked.IsDisposed)
                    {
                        TrackedRoots.RemoveAt(index);
                    }
                }

                // Native root creation and weak registration are one lifecycle
                // admission step. Teardown either runs first and rejects this
                // creation, or waits and includes the raw root in its snapshot.
                var state = LuauState.Create(stateOptions);
                TrackedRoots.Add(new WeakReference<LuauState>(state));
                return state;
            }
        }

        /// <summary>
        /// Disposes every still-live root created through <see cref="CreateState"/>.
        /// Tracking is weak and does not replace caller ownership.
        /// </summary>
        internal static void DisposeTrackedRoots()
        {
            LuauState[] roots;
            lock (TrackedRootsGate)
            {
                trackedRootAdmissionStopping = true;
                var liveRoots = new List<LuauState>(TrackedRoots.Count);
                for (var index = 0; index < TrackedRoots.Count; index++)
                {
                    if (TrackedRoots[index].TryGetTarget(out var root) && !root.IsDisposed)
                    {
                        liveRoots.Add(root);
                    }
                }

                TrackedRoots.Clear();
                roots = liveRoots.ToArray();
            }

            for (var index = 0; index < roots.Length; index++)
            {
                roots[index].Dispose();
            }
        }

#if UNITY_EDITOR
        internal static void ResetTrackedRootAdmissionAfterDrainForTests()
        {
            lock (TrackedRootsGate)
            {
                if (TrackedRoots.Count != 0)
                {
                    throw new InvalidOperationException(
                        "Tracked root admission can only be reset after a completed root drain.");
                }

                trackedRootAdmissionStopping = false;
            }
        }
#endif

        static LuauStateOptions ResolveStateOptions(LuauUnityOptions options)
        {
            var stateOptions = options.StateOptions
                ?? throw new ArgumentNullException(nameof(options.StateOptions));

            if (options.UseFirstPartyBytecode)
            {
                if (stateOptions.BytecodePolicy != LuauBytecodePolicy.Reject ||
                    stateOptions.BytecodeValidator != null)
                {
                    throw new InvalidOperationException(
                        $"{nameof(LuauUnityOptions.UseFirstPartyBytecode)} cannot be combined with an existing " +
                        $"{nameof(LuauStateOptions.BytecodePolicy)} or {nameof(LuauStateOptions.BytecodeValidator)}. " +
                        "Leave generated first-party validation disabled when supplying a custom bytecode validator.");
                }

                // Resolve the preloaded, pure-managed validator before the
                // native state is allocated. The record clone preserves every
                // caller-supplied limit and execution setting.
                stateOptions = stateOptions with
                {
                    BytecodePolicy = LuauBytecodePolicy.RequireValidator,
                    BytecodeValidator = FirstPartyBytecodeManifestCache.GetValidatorOrThrow(),
                };
            }

            var executionOptions = stateOptions.DefaultExecutionOptions;
            var scheduler = options.ContinuationScheduler
                ?? executionOptions.ContinuationScheduler;

            if (scheduler == null && options.CaptureUnitySynchronizationContext)
            {
                var synchronizationContext = SynchronizationContext.Current;
                if (synchronizationContext == null)
                {
                    throw new InvalidOperationException(
                        "No Unity SynchronizationContext is available. Create the Luau state on the Unity main thread, " +
                        "provide a continuation scheduler, or explicitly disable synchronization-context capture.");
                }

                scheduler = new LuauSynchronizationContextScheduler(synchronizationContext);
            }

            if (scheduler == null || ReferenceEquals(scheduler, executionOptions.ContinuationScheduler))
            {
                return stateOptions;
            }

            return stateOptions with
            {
                DefaultExecutionOptions = executionOptions with
                {
                    ContinuationScheduler = scheduler,
                },
            };
        }

        public static void RegisterPrint(LuauState state, Action<string> log = null)
        {
            RegisterPrint(
                state,
                log,
                LuauUnityOptions.DefaultMaxPrintArguments,
                LuauUnityOptions.DefaultMaxPrintUtf8Bytes,
                LuauUnityOptions.DefaultMaxPrintMessagesPerSecond);
        }

        /// <summary>
        /// Registers a bounded Unity logging implementation of Luau's
        /// <c>print</c> function.
        /// </summary>
        public static void RegisterPrint(
            LuauState state,
            Action<string> log,
            int maxArguments,
            int maxUtf8Bytes)
        {
            RegisterPrint(
                state,
                log,
                maxArguments,
                maxUtf8Bytes,
                LuauUnityOptions.DefaultMaxPrintMessagesPerSecond);
        }

        /// <summary>
        /// Registers a size- and rate-bounded Unity logging implementation of
        /// Luau's <c>print</c> function.
        /// </summary>
        public static void RegisterPrint(
            LuauState state,
            Action<string> log,
            int maxArguments,
            int maxUtf8Bytes,
            int? maxMessagesPerSecond)
        {
            if (state == null)
            {
                throw new ArgumentNullException(nameof(state));
            }

            if (maxArguments <= 0)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(maxArguments),
                    maxArguments,
                    "The print argument limit must be positive.");
            }

            if (maxUtf8Bytes <= 0)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(maxUtf8Bytes),
                    maxUtf8Bytes,
                    "The print output limit must be positive.");
            }

            if (maxMessagesPerSecond.HasValue && maxMessagesPerSecond.Value <= 0)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(maxMessagesPerSecond),
                    maxMessagesPerSecond,
                    "The print message rate limit must be positive when configured.");
            }

            log = log ?? Debug.Log;
            var rateLimiter = maxMessagesPerSecond.HasValue
                ? new PrintRateLimiter(maxMessagesPerSecond.Value)
                : null;

            state["print"] = state.CreateFunction("print", context =>
            {
                if (rateLimiter != null && !rateLimiter.TryAcquire())
                {
                    return;
                }

                if (context.ArgumentCount == 0)
                {
                    log(string.Empty);
                    return;
                }

                log(FormatPrintMessage(context, maxArguments, maxUtf8Bytes));
            });
        }

        static string FormatPrintMessage(
            LuauCallContext context,
            int maxArguments,
            int maxUtf8Bytes)
        {
            var builder = new StringBuilder(Math.Min(maxUtf8Bytes, 256));
            var emittedUtf8Bytes = 0;
            var valueCount = context.ArgumentCount;
            var valuesToFormat = Math.Min(valueCount, maxArguments);
            var truncated = valueCount > valuesToFormat;

            for (var index = 0; index < valuesToFormat; index++)
            {
                if (index > 0)
                {
                    if (emittedUtf8Bytes >= maxUtf8Bytes)
                    {
                        truncated = true;
                        break;
                    }

                    builder.Append('\t');
                    emittedUtf8Bytes++;
                }

                var remainingUtf8Bytes = maxUtf8Bytes - emittedUtf8Bytes;
                if (remainingUtf8Bytes <= 0)
                {
                    truncated = true;
                    break;
                }

                var value = context.ToDisplayString(
                    index,
                    remainingUtf8Bytes,
                    out var valueWasTruncated);
                builder.Append(value);
                emittedUtf8Bytes += Encoding.UTF8.GetByteCount(value);

                if (valueWasTruncated)
                {
                    truncated = true;
                    break;
                }
            }

            if (truncated)
            {
                AppendTruncationMarker(builder, ref emittedUtf8Bytes, maxUtf8Bytes);
            }

            return builder.ToString();
        }

        static void AppendTruncationMarker(
            StringBuilder builder,
            ref int emittedUtf8Bytes,
            int maxUtf8Bytes)
        {
            var markerBytes = Math.Min(3, maxUtf8Bytes);
            while (emittedUtf8Bytes > maxUtf8Bytes - markerBytes && builder.Length > 0)
            {
                var lastIndex = builder.Length - 1;
                var characterCount = 1;
                var byteCount = GetUtf8ByteCount(builder[lastIndex]);

                if (char.IsLowSurrogate(builder[lastIndex]) &&
                    lastIndex > 0 &&
                    char.IsHighSurrogate(builder[lastIndex - 1]))
                {
                    characterCount = 2;
                    byteCount = 4;
                }

                builder.Length -= characterCount;
                emittedUtf8Bytes -= byteCount;
            }

            for (var index = 0; index < markerBytes; index++)
            {
                builder.Append('.');
            }

            emittedUtf8Bytes += markerBytes;
        }

        static int GetUtf8ByteCount(char character)
        {
            if (character <= '\u007f')
            {
                return 1;
            }

            return character <= '\u07ff' ? 2 : 3;
        }

        sealed class PrintRateLimiter
        {
            readonly object gate = new();
            readonly int maxMessagesPerSecond;
            long windowStarted = System.Diagnostics.Stopwatch.GetTimestamp();
            int messageCount;

            public PrintRateLimiter(int maxMessagesPerSecond)
            {
                this.maxMessagesPerSecond = maxMessagesPerSecond;
            }

            public bool TryAcquire()
            {
                lock (gate)
                {
                    var now = System.Diagnostics.Stopwatch.GetTimestamp();
                    if (now - windowStarted >= System.Diagnostics.Stopwatch.Frequency)
                    {
                        windowStarted = now;
                        messageCount = 0;
                    }

                    if (messageCount >= maxMessagesPerSecond)
                    {
                        return false;
                    }

                    messageCount++;
                    return true;
                }
            }
        }

        static void OpenUnityStandardLibraries(LuauState state)
        {
            state.OpenBaseLibrary();
            state.OpenMathLibrary();
            state.OpenTableLibrary();
            state.OpenStringLibrary();
            state.OpenCoroutineLibrary();
            state.OpenBit32Library();
            state.OpenUtf8Library();
            state.OpenBufferLibrary();
            state.OpenVectorLibrary();
            state.OpenIntegerLibrary();
        }
    }
}
